/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doung;

import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JDialog;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;



/**
 *
 * @author BimaCos
 */
public class crud extends javax.swing.JFrame {
    int xMouse,yMouse;
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabmodel;
    Connection cn = koneksiDB.getKoneksi();
    JasperReport jasperReport;
    JasperDesign jasperDesign;
    JasperPrint jasperPrint;
    HashMap param = new HashMap();
    
    public crud() {
        initComponents();
        judul();
        tampildata();
        
        update.setEnabled(false);
        delete.setEnabled(false);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ntoko = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        namap = new javax.swing.JTextField();
        notlp = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_pelanggan = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        update = new javax.swing.JButton();
        back = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        save = new javax.swing.JButton();
        report1 = new javax.swing.JButton();
        search = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        hargad = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        hitung = new javax.swing.JButton();
        jumlah1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jumlah2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setToolTipText("");
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 20, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 40, 30));

        ntoko.setBackground(new java.awt.Color(36, 12, 0));
        ntoko.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ntoko.setForeground(new java.awt.Color(255, 255, 255));
        ntoko.setBorder(null);
        ntoko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntokoActionPerformed(evt);
            }
        });
        getContentPane().add(ntoko, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 160, 30));

        alamat.setBackground(new java.awt.Color(36, 12, 0));
        alamat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alamat.setForeground(new java.awt.Color(255, 255, 255));
        alamat.setBorder(null);
        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 160, 30));

        jumlah.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jumlah.setBorder(null);
        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });
        getContentPane().add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 90, 20));

        namap.setBackground(new java.awt.Color(36, 12, 0));
        namap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        namap.setForeground(new java.awt.Color(255, 255, 255));
        namap.setBorder(null);
        namap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namapActionPerformed(evt);
            }
        });
        getContentPane().add(namap, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 160, 30));

        notlp.setBackground(new java.awt.Color(36, 12, 0));
        notlp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        notlp.setForeground(new java.awt.Color(255, 255, 255));
        notlp.setBorder(null);
        notlp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notlpActionPerformed(evt);
            }
        });
        getContentPane().add(notlp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 160, 30));
        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 190, 1));
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 190, 1));

        tb_pelanggan.setForeground(new java.awt.Color(88, 29, 0));
        tb_pelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_pelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_pelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_pelanggan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 570, 280));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 190, 1));
        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 570, 1));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 190, 1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doung/sans.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doung/home.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nama Pelanggan");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 150, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doung/network.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 40, 30));

        jLabel8.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Coklat          :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 80, 40));

        jLabel9.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nama Toko");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 130, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doung/ringing.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, -1, -1));

        reset.setBackground(new java.awt.Color(255, 208, 101));
        reset.setFont(new java.awt.Font("Tekton Pro Cond", 1, 24)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doung/settings (1).png"))); // NOI18N
        reset.setText("Reset");
        reset.setBorder(null);
        reset.setBorderPainted(false);
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 500, 100, 40));

        update.setBackground(new java.awt.Color(255, 208, 101));
        update.setFont(new java.awt.Font("Tekton Pro Cond", 1, 24)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doung/pencil.png"))); // NOI18N
        update.setText("Edit");
        update.setBorder(null);
        update.setBorderPainted(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, 100, 40));

        back.setBackground(new java.awt.Color(255, 208, 101));
        back.setFont(new java.awt.Font("Tekton Pro Cond", 1, 24)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doung/exit.png"))); // NOI18N
        back.setText("Back");
        back.setBorder(null);
        back.setBorderPainted(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 100, 40));

        delete.setBackground(new java.awt.Color(255, 208, 101));
        delete.setFont(new java.awt.Font("Tekton Pro Cond", 1, 24)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doung/rubbish-bin.png"))); // NOI18N
        delete.setText("Delete");
        delete.setBorder(null);
        delete.setBorderPainted(false);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, 100, 40));

        save.setBackground(new java.awt.Color(255, 208, 101));
        save.setFont(new java.awt.Font("Tekton Pro Cond", 1, 24)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doung/icon.png"))); // NOI18N
        save.setText("Save");
        save.setBorder(null);
        save.setBorderPainted(false);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, 100, 40));

        report1.setBackground(new java.awt.Color(255, 208, 101));
        report1.setFont(new java.awt.Font("Tekton Pro Cond", 1, 24)); // NOI18N
        report1.setForeground(new java.awt.Color(255, 255, 255));
        report1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doung/newspaper.png"))); // NOI18N
        report1.setText("Report");
        report1.setBorder(null);
        report1.setBorderPainted(false);
        report1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report1ActionPerformed(evt);
            }
        });
        getContentPane().add(report1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 100, 40));

        search.setBackground(new java.awt.Color(36, 12, 0));
        search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setBorder(null);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 530, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doung/magnifying-glass.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 115, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doung/online-store.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doung/donut (2).png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("No Telepon");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 130, 40));

        jLabel17.setFont(new java.awt.Font("Tekton Pro Cond", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("\"Honesty is the key to a halal success\"");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 470, -1));

        jLabel19.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Rp.");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, -1, -1));

        hargad.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        hargad.setForeground(new java.awt.Color(255, 255, 255));
        hargad.setText("0");
        getContentPane().add(hargad, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 150, -1));

        jLabel18.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Topping & Jumlah");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 120, 40));

        jLabel7.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Alamat");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 130, 40));

        hitung.setBackground(new java.awt.Color(255, 208, 101));
        hitung.setFont(new java.awt.Font("Tekton Pro Cond", 1, 24)); // NOI18N
        hitung.setForeground(new java.awt.Color(255, 255, 255));
        hitung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doung/calculator.png"))); // NOI18N
        hitung.setBorder(null);
        hitung.setBorderPainted(false);
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        getContentPane().add(hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 500, 40, 40));

        jumlah1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jumlah1.setBorder(null);
        jumlah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah1ActionPerformed(evt);
            }
        });
        getContentPane().add(jumlah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 90, 20));

        jLabel21.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Vanilla         :");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 90, 40));

        jumlah2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jumlah2.setBorder(null);
        jumlah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah2ActionPerformed(evt);
            }
        });
        getContentPane().add(jumlah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 550, 90, 20));

        jLabel20.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Strawberry :");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 90, 40));

        jLabel13.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Total");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doung/form.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        if(JOptionPane.showConfirmDialog(null,"Yakin Mau Keluar?","Keluar",JOptionPane.YES_NO_OPTION)==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void namapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namapActionPerformed

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    private void ntokoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntokoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ntokoActionPerformed

    private void notlpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notlpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notlpActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        if(JOptionPane.showConfirmDialog(null,"Yakin Mau Keluar?","Keluar",JOptionPane.YES_NO_OPTION)==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jPanel1MouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
         if(JOptionPane.showConfirmDialog(null,"Ingin Kembali?","Kembali",JOptionPane.YES_NO_OPTION)==0)
        {
         halaman_utm ht = new halaman_utm();
                ht.setVisible(true);
                this.dispose();
        }

    }//GEN-LAST:event_backActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
         try {
              st = cn.createStatement();
              st.executeUpdate("UPDATE tb_order SET nama_p='" + namap.getText() + "', alamat_p='" + alamat.getText() + "', namat_p='" + ntoko.getText() + "', notlp_p='" + notlp.getText() + "', coklat_p='" + jumlah.getText() + "',strawberry_p='"+jumlah1.getText()+"',vanilla_p='"+jumlah2.getText()+"' where IDPelanggan='" + tabmodel.getValueAt(tb_pelanggan.getSelectedRow(), 0) + "';");
              reset();
              JOptionPane.showMessageDialog(null, "data berhasil diubah");
              tampildata();   
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_updateActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        reset();
    }//GEN-LAST:event_resetActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
          try{
            int jawab;
            if ((jawab = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin ingin menghapus data?", "konfirmasi", JOptionPane.YES_NO_OPTION) ) == 0);
            {
              st = cn.createStatement();
              st.executeUpdate("delete from tb_order where nama_p='" + tabmodel.getValueAt(tb_pelanggan.getSelectedRow(), 1) + "'");
              tampildata();
              reset();
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
       if (namap.getText().equals("") || alamat.getText().equals("") || 
                ntoko.getText().equals("") || notlp.getText().equals("") ||
                jumlah.getText().equals("") ||  jumlah1.getText().equals("") || jumlah2.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Silahkan isi data terlebih dahulu");
        }else{
            simpan();
        } 
    }//GEN-LAST:event_saveActionPerformed

    private void report1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report1ActionPerformed
      try {
            File file = new File("src/doung/reportpelanggan.jrxml");
            jasperDesign = JRXmlLoader.load(file);
            jasperReport = JasperCompileManager.compileReport(jasperDesign);
            jasperPrint = JasperFillManager.fillReport(jasperReport, param,    koneksiDB.getKoneksi());
            JasperViewer.viewReport(jasperPrint, false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_report1ActionPerformed

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void tb_pelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_pelangganMouseClicked
       namap.setText(tabmodel.getValueAt(tb_pelanggan.getSelectedRow(), 1) + "");
        alamat.setText(tabmodel.getValueAt(tb_pelanggan.getSelectedRow(), 2) + "");
        ntoko.setText(tabmodel.getValueAt(tb_pelanggan.getSelectedRow(), 3) + "");
        notlp.setText(tabmodel.getValueAt(tb_pelanggan.getSelectedRow(), 4) + "");
        jumlah.setText(tabmodel.getValueAt(tb_pelanggan.getSelectedRow(), 5) + "");
        jumlah1.setText(tabmodel.getValueAt(tb_pelanggan.getSelectedRow(), 6) + "");
        jumlah2.setText(tabmodel.getValueAt(tb_pelanggan.getSelectedRow(), 7) + "");
        hargad.setText(tabmodel.getValueAt(tb_pelanggan.getSelectedRow(), 8) + "");
        
        save.setEnabled(false);
        delete.setEnabled(true);
        update.setEnabled(true);
    }//GEN-LAST:event_tb_pelangganMouseClicked

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
         try {
            tabmodel.getDataVector().removeAllElements();
            tabmodel.fireTableDataChanged();
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM tb_order WHERE IDPelanggan like '%"+search.getText()+"%'or nama_p like '%" + search.getText() + "%' or  alamat_p like '%" + search.getText() + "%' or namat_p like '%" + search.getText() + "%' or notlp_p like '%" + search.getText() + "%' or jumlah_p like '%" + search.getText() + "%' or topping_p like '%" + search.getText() +  "%'");
            while (rs.next()){
                Object[] data = {
                    
                    rs.getString("IDPelanggan"),
                    rs.getString("nama_p"),
                    rs.getString("alamat_p"),
                    rs.getString("namat_p"),
                    rs.getString("notlp_p"),
                    rs.getString("jumlah_p"),
                    rs.getString("topping_p"),
                    rs.getString("harga_p"),
            
                };
                tabmodel.addRow(data);
            }
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_searchKeyReleased

    private void jumlah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlah1ActionPerformed

    private void jumlah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlah2ActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
       int hasil,a,b,c,e,f,g,total;
        if (jumlah.getText().equals("") || jumlah1.getText().equals("") || jumlah2.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Silahkan Isi jumlah terlebih dahulu");
        }else {
        a=Integer.parseInt(jumlah.getText());
        b=Integer.parseInt(jumlah1.getText());
        c=Integer.parseInt(jumlah2.getText());
        
        hasil=(a*5000)+(b*5000)+(c*5000);
         hargad.setText(String.valueOf(hasil));
         
    }//GEN-LAST:event_hitungActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton back;
    private javax.swing.JButton delete;
    private javax.swing.JLabel hargad;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField jumlah1;
    private javax.swing.JTextField jumlah2;
    private javax.swing.JTextField namap;
    private javax.swing.JTextField notlp;
    private javax.swing.JTextField ntoko;
    private javax.swing.JButton report1;
    private javax.swing.JButton reset;
    private javax.swing.JButton save;
    private javax.swing.JTextField search;
    private javax.swing.JTable tb_pelanggan;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    public void simpan(){
        try {
            st = cn.createStatement();
           String sql = "INSERT INTO tb_order VALUES (null,'" + namap.getText() + "', '" + alamat.getText() + "', '" + ntoko.getText() + "', '" + notlp.getText() + "', '" +jumlah.getText()+ "','" +jumlah1.getText()+ "','" +jumlah2.getText()+ "','"+hargad.getText()+"')";
            st.execute(sql);   

            tampildata();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            
            namap.setText("");
            alamat.setText("");
            ntoko.setText("");
            notlp.setText("");
            jumlah.setText("");
            hargad.setText("0");
            jumlah1.setText("");
            jumlah2.setText("");
            
            
        } catch (Exception e){
            e.printStackTrace();
        }
    }
    
    public void reset (){
        namap.setText("");
        alamat.setText("");
        ntoko.setText("");
        notlp.setText("");
        jumlah.setText("");
        jumlah1.setText("");
        jumlah2.setText("");
        hargad.setText("0");
        
        save.setEnabled(true);
        update.setEnabled(false);
        delete.setEnabled(false); 
    }
    
     public void judul (){
        Object [] judul = {"ID Pelanggan", "Nama", "Alamat", "Nama Toko", "No Telepon", "Coklat" , "Strawberry", "Vanilla" , "Harga"};
        tabmodel = new DefaultTableModel(null, judul);
        tb_pelanggan.setModel(tabmodel);
    }
     
     public void tampildata() {
        try {
            st = cn.createStatement();
            tabmodel.getDataVector().removeAllElements();
            tabmodel.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM tb_order ORDER BY IDPelanggan");
            while (rs.next() ){
                Object[] data = {
                    rs.getString("IDPelanggan"),
                    rs.getString("nama_p"),
                    rs.getString("alamat_p"),
                    rs.getString("namat_p"),
                    rs.getString("notlp_p"),
                    rs.getString("coklat_p"),
                    rs.getString("strawberry_p"),
                    rs.getString("vanilla_p"),
                    rs.getString("harga_p"),
                    
                };
                tabmodel.addRow(data);
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }

 
}

