/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doung;


import com.sun.javafx.collections.MappingChange.Map;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.HashMap;
import javax.swing.JDialog;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author BimaCos
 */
public class salesd extends javax.swing.JFrame {
    int xMouse,yMouse;
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabmodel,tabmodel1;
    Connection cn = koneksiDB.getKoneksi();
    JasperReport jasperReport;
    JasperDesign jasperDesign;
    JasperPrint jasperPrint;
    HashMap param = new HashMap();
    
    
    java.util.Date tglsekarang = new java.util.Date();
private SimpleDateFormat smp = new SimpleDateFormat("dd MMMMMMMMM yyyy", Locale.getDefault());

private String tanggal = smp.format(tglsekarang);

    /**
     * Creates new form salesd
     */
    public salesd() {
        initComponents();
        delete.setEnabled(false);
        date.setText(tanggal);
        setJam();
           judul();
           tampildata();
           judul1();
           tampildata1();
         total.setEnabled(false);
         kembalian.setEnabled(false);
         id.setEnabled(false);
       
         
      
    }
    public final void setJam(){
ActionListener taskPerformer;
        taskPerformer = new ActionListener() {
            
            @Override
            public void actionPerformed(ActionEvent evt) {
                String nol_jam = "", nol_menit = "",nol_detik = "";
                
                java.util.Date dateTime = new java.util.Date();
                int nilai_jam = dateTime.getHours();
                int nilai_menit = dateTime.getMinutes();
                int nilai_detik = dateTime.getSeconds();
                
                if(nilai_jam <= 9) nol_jam= "0";
                if(nilai_menit <= 9) nol_menit= "0";
                if(nilai_detik <= 9) nol_detik= "0";
                
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                
                time.setText(jam+":"+menit+":"+detik+"");
            }
        };
        new Timer(1000, taskPerformer).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        report = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_orderan = new javax.swing.JTable();
        Total = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        bayar = new javax.swing.JTextField();
        Kembali1 = new javax.swing.JLabel();
        Kembali2 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        Kembali3 = new javax.swing.JLabel();
        kembalian = new javax.swing.JTextField();
        biaya = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doung/donut (2).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tekton Pro Cond", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("\"Honesty is a truth.\"");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 260, 70));

        report.setBackground(new java.awt.Color(255, 208, 101));
        report.setFont(new java.awt.Font("Tekton Pro Cond", 1, 24)); // NOI18N
        report.setForeground(new java.awt.Color(255, 255, 255));
        report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doung/newspaper.png"))); // NOI18N
        report.setText("Report");
        report.setBorder(null);
        report.setBorderPainted(false);
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });
        getContentPane().add(report, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, 40));

        back.setBackground(new java.awt.Color(255, 208, 101));
        back.setFont(new java.awt.Font("Tekton Pro Cond", 1, 24)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doung/exit.png"))); // NOI18N
        back.setText("Back");
        back.setBorder(null);
        back.setBorderPainted(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 40));

        tb_orderan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_orderan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_orderanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_orderan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 440, 110));

        Total.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        Total.setForeground(new java.awt.Color(255, 255, 255));
        Total.setText("Total");
        getContentPane().add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 150, 40));

        total.setBackground(new java.awt.Color(255, 206, 101));
        total.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 255));
        total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 160, 30));

        bayar.setBackground(new java.awt.Color(255, 206, 101));
        bayar.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        bayar.setForeground(new java.awt.Color(255, 255, 255));
        bayar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });
        getContentPane().add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 160, 30));

        Kembali1.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        Kembali1.setForeground(new java.awt.Color(255, 255, 255));
        Kembali1.setText("Pay");
        getContentPane().add(Kembali1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 150, 40));

        Kembali2.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        Kembali2.setForeground(new java.awt.Color(255, 255, 255));
        Kembali2.setText("Change");
        getContentPane().add(Kembali2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 150, 40));

        time.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        time.setText("Time");
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 150, 40));

        date.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setText("Date");
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 150, 40));

        delete.setBackground(new java.awt.Color(255, 208, 101));
        delete.setFont(new java.awt.Font("Tekton Pro Cond", 1, 24)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doung/settings (1).png"))); // NOI18N
        delete.setBorder(null);
        delete.setBorderPainted(false);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 60, 40));

        id.setBackground(new java.awt.Color(255, 206, 101));
        id.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 160, 30));

        Kembali3.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        Kembali3.setForeground(new java.awt.Color(255, 255, 255));
        Kembali3.setText("ID");
        getContentPane().add(Kembali3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 150, 40));

        kembalian.setBackground(new java.awt.Color(255, 206, 101));
        kembalian.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        kembalian.setForeground(new java.awt.Color(255, 255, 255));
        kembalian.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalianActionPerformed(evt);
            }
        });
        getContentPane().add(kembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 160, 30));

        biaya.setBackground(new java.awt.Color(255, 208, 101));
        biaya.setFont(new java.awt.Font("Tekton Pro Cond", 1, 24)); // NOI18N
        biaya.setForeground(new java.awt.Color(255, 255, 255));
        biaya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doung/money-bag-with-dollar-symbol.png"))); // NOI18N
        biaya.setBorder(null);
        biaya.setBorderPainted(false);
        biaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biayaActionPerformed(evt);
            }
        });
        getContentPane().add(biaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 90, 40));

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setToolTipText("");
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("X");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 20, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 40, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doung/form.png"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
      try {
            File file = new File("src/doung/struk.jrxml");
            jasperDesign = JRXmlLoader.load(file);
            param.put("idpel",id.getText());
            jasperReport = JasperCompileManager.compileReport(jasperDesign);
            jasperPrint = JasperFillManager.fillReport(jasperReport, param,    koneksiDB.getKoneksi());
            JasperViewer.viewReport(jasperPrint, false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_reportActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        if(JOptionPane.showConfirmDialog(null,"Ingin Kembali?","Kembali",JOptionPane.YES_NO_OPTION)==0)
        {
            halaman_utm ht = new halaman_utm();
            ht.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_backActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void biayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biayaActionPerformed
        int a = Integer.parseInt(total.getText());
        int b = Integer.parseInt(bayar.getText());
        
        if(total.getText().equals("") || bayar.getText().equals("")) {
                 JOptionPane.showMessageDialog(null, "Silahkan isi data terlebih dahulu");
        }else if(a >= b){
            
                   JOptionPane.showMessageDialog(null, "Uang Anda Kurang");
            
        
        }else{
                kembali();
        }
    }//GEN-LAST:event_biayaActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        if(JOptionPane.showConfirmDialog(null,"Yakin Mau Keluar?","Keluar",JOptionPane.YES_NO_OPTION)==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        if(JOptionPane.showConfirmDialog(null,"Yakin Mau Keluar?","Keluar",JOptionPane.YES_NO_OPTION)==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse,y - yMouse);
    
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
           xMouse = evt.getX();
           yMouse = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bayarActionPerformed

    private void kembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembalianActionPerformed

    private void tb_orderanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_orderanMouseClicked
        // TODO add your handling code here: namap.setText(tabmodel.getValueAt(tb_pelanggan.getSelectedRow(), 1) + "");
        id.setText(tabmodel.getValueAt(tb_orderan.getSelectedRow(), 0) + "");
        total.setText(tabmodel.getValueAt(tb_orderan.getSelectedRow(), 7) + "");
        delete.setEnabled(true);
       
    }//GEN-LAST:event_tb_orderanMouseClicked

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        total.setText("");
            bayar.setText("");
            kembalian.setText("");
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salesd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salesd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salesd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salesd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new salesd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Kembali1;
    private javax.swing.JLabel Kembali2;
    private javax.swing.JLabel Kembali3;
    private javax.swing.JLabel Total;
    private javax.swing.JButton back;
    private javax.swing.JTextField bayar;
    private javax.swing.JButton biaya;
    private javax.swing.JLabel date;
    private javax.swing.JButton delete;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kembalian;
    private javax.swing.JButton report;
    private javax.swing.JTable tb_orderan;
    private javax.swing.JLabel time;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
  public void judul (){
        Object [] judul = {"ID Pelanggan", "Nama","No Telepon","Nama Toko","Coklat" , "Strawberry" , "Vanilla" , "Harga"};
        tabmodel = new DefaultTableModel(null, judul);
        tb_orderan.setModel(tabmodel);
  }
    public void tampildata() {
        try {
            st = cn.createStatement();
            tabmodel.getDataVector().removeAllElements();
            tabmodel.fireTableDataChanged();
            rs = st.executeQuery("SELECT IDPelanggan,nama_p,notlp_p,namat_p,coklat_p,strawberry_p,vanilla_p,harga_p FROM tb_order");
            while (rs.next() ){
                Object[] data = {
                    rs.getString("IDPelanggan"),
                    rs.getString("nama_p"),
                    rs.getString("notlp_p"),
                    rs.getString("namat_p"),
                    rs.getString("coklat_p"),
                    rs.getString("strawberry_p"),
                    rs.getString("vanilla_p"),
                    rs.getString("harga_p"),
                    
                };
                tabmodel.addRow(data);
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }
    
    public void judul1(){
        Object [] judul = {"Nama", "Total","Bayar", "Kembali","Tgl Bayar","Waktu Bayar"};
        tabmodel1 = new DefaultTableModel(null, judul);
    
     
    }
    
      public void tampildata1() {
        try {
            st = cn.createStatement();
            tabmodel1.getDataVector().removeAllElements();
            tabmodel1.fireTableDataChanged();
            rs = st.executeQuery("SELECT pelanggan.nama_p , pelanggan.Totalb , pelanggan.BayarB , pelanggan.Kembali , pelanggan.tgl_bayar , pelanggan.waktu_bayar FROM pelanggan");
            while (rs.next() ){
                Object[] data = {
                    rs.getString("nama_p"),
                    rs.getString("Totalb"),
                    rs.getString("BayarB"),
                    rs.getString("Kembali"),
                    rs.getString("tgl_bayar"),
                    rs.getString("waktu_bayar"),
              
                };
                tabmodel1.addRow(data);
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }
   public void kembali(){
           
       try {
               int kembali ,d,c;
               
               d=Integer.parseInt(total.getText());
               c=Integer.parseInt(bayar.getText());
               
               kembali = c - d;
               kembalian.setText(String.valueOf(kembali));
           
               
           st = cn.createStatement();
           String sql = "INSERT INTO tb_bayar VALUES ('"+id.getText()+"','" + total.getText() + "', '" + bayar.getText() + "', '" + kembalian.getText() + "','"+date.getText()+"','"+time.getText()+"')";
           st.execute(sql);
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            judul1();
            tampildata1();
            
            
           
            
            
        } catch (Exception e){
            e.printStackTrace();
        }
   }   
}
